# Generated by Django 5.1.3 on 2024-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_categoria_alter_comentario_texto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='resposta_a',
            new_name='comentario_resposta',
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
