# Generated by Django 3.2.8 on 2024-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_rename_resposta_a_comentario_comentario_resposta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='comentario_resposta',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
    ]
