# Generated by Django 5.1.3 on 2024-11-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_alter_categoria_options_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lojas.categoria'),
        ),
    ]
