# Generated by Django 5.0.4 on 2024-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_data_nascimento_alter_cliente_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
